[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["mongoose", "express", "sharp"]
  included_files = ["config.env"]
  node_bundler = "esbuild"

[functions.server]
  memory = 1024
  timeout = 10

[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
